# Generated by Django 6.0.6 on 2026-08-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_movie_like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
